name: YWAM Emerge
favicon: null
layout_spectrum: 0.2041468599345535
typography_spectrum: 0.20885712606832385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.31899697659537196
  lightness: 0.8708765069022775
  saturation: 0.40267612785100937
  rhythmicContrast: 0.12546715280041099
purpose: []
