name: YWAM Emerge
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59583
title: YWAM Emerge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2d2d2'
    - '#5c85a0'
    - '#000000'
    - '#3c3e3d'
    - '#fffde9'
  brandStrength: 0
  lightness: 0
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
