name: YWAM Emerge
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20885712606832385
title: YWAM Emerge
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2d2d2'
    - '#5c85a0'
    - '#000000'
    - '#3c3e3d'
    - '#fffde9'
  brandStrength: 1
  lightness: 0.8708765069022775
  saturation: 0.125
  rhythmicContrast: 0.12546715280041099
purpose: []
